### ISSUE TITLE
name always is `Error`

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/plugin-error#2] opened 2015-06-28 19:08 UTC
Name of created error always is `Error` not `PluginError` by default.
It [never sets the name](https://github.com/jonschlinkert/plugin-error/blob/master/index.js#L49) to `PluginError` here. So it is `Error` until we `{name: 'MyError'}`.

``` js
var PluginError = require('plugin-error')
var err = new PluginError('foo', 'bar baz')
console.log(String(err))
```

outputs

```
[charlike@archlinux ~/dev]$ node test.js 
Error in plugin "foo"
Message:
    bar baz
```

**Comment by jonschlinkert** [comment] 2015-06-29 13:12
hmm, I might not have time to look at this for a few days or longer. if you feel like doing a pr that would be great, otherwise I'll try to take a look later this week or weekend

**Comment by demurgos** [comment] 2017-12-28 01:48
I don't remember the exact details but it may be caused by the call to the native error constructor. I remember that it has some special behavior that may reset some properties.

**Comment by phated** [comment] 2017-12-29 20:55
I checked this behavior in gulp-util and it's the same.  I'm going to close this unless there's a compelling reason (and hopefully a PR)

**Closed as completed by phated** 2017-12-29 20:55 UTC
